// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-plants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
var EXTERNAL_URL = "https://mcinlbefwyysuljrluln.supabase.co";
var EXTERNAL_KEY = "sb_publishable_te0Gqsd8aIjIPrO2LrweCQ_Ga7x1FqW";
async function queryExternal(pathAndQuery) {
  const res = await fetch(`${EXTERNAL_URL}/rest/v1/${pathAndQuery}`, {
    headers: {
      apikey: EXTERNAL_KEY,
      Authorization: `Bearer ${EXTERNAL_KEY}`,
      Accept: "application/json"
    }
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Supabase ${res.status}: ${body.slice(0, 200)}`);
  }
  return res.json();
}

// src/lib/mcp/tools/list-plants.ts
var list_plants_default = defineTool({
  name: "list_plants",
  title: "List plants",
  description: "List plants in the TreeKingdom encyclopedia. Optionally filter by category (e.g. tropical, succulent, flower, herb, tree, cactus, indoor, outdoor) or by a text query matched against Thai/English names.",
  inputSchema: {
    category: z.string().optional().describe("Category key to filter by."),
    query: z.string().optional().describe("Text query matched against plant names."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, query, limit }) => {
    const params = new URLSearchParams();
    params.set("select", "id,name,category,description,emoji,care,levels,tags,sort_order");
    params.set("order", "sort_order.asc,created_at.asc");
    params.set("limit", String(limit ?? 50));
    if (category) params.set("category", `eq.${category}`);
    if (query) {
      const q = query.replace(/[%,]/g, "");
      params.set("or", `(name->>th.ilike.*${q}*,name->>en.ilike.*${q}*)`);
    }
    const rows = await queryExternal(`plants?${params}`);
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { plants: rows }
    };
  }
});

// src/lib/mcp/tools/get-plant.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_plant_default = defineTool2({
  name: "get_plant",
  title: "Get plant",
  description: "Get a single plant by id, including its varieties.",
  inputSchema: {
    id: z2.string().min(1).describe("Plant id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const idEnc = encodeURIComponent(id);
    const [plants, varieties] = await Promise.all([
      queryExternal(`plants?id=eq.${idEnc}&select=*&limit=1`),
      queryExternal(`plant_varieties?plant_id=eq.${idEnc}&select=*&order=sort_order.asc`)
    ]);
    const plant = plants?.[0];
    if (!plant) {
      return { content: [{ type: "text", text: `Plant ${id} not found` }], isError: true };
    }
    const result = { ...plant, varieties };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { plant: result }
    };
  }
});

// src/lib/mcp/tools/list-supplies.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_supplies_default = defineTool3({
  name: "list_supplies",
  title: "List supplies",
  description: "List store supplies/products. Optionally filter by category, or by is_lucky=true to get only lucky/auspicious plants.",
  inputSchema: {
    category: z3.string().optional().describe("Category key to filter by."),
    is_lucky: z3.boolean().optional().describe("If true, only return items flagged as lucky."),
    query: z3.string().optional().describe("Text query matched against product names."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, is_lucky, query, limit }) => {
    const params = new URLSearchParams();
    params.set(
      "select",
      "id,name,category,description,price,compare_at_price,stock,emoji,is_lucky,lucky,plant_id,variety_id,tags,sort_order"
    );
    params.set("order", "sort_order.asc,created_at.asc");
    params.set("limit", String(limit ?? 50));
    if (category) params.set("category", `eq.${category}`);
    if (typeof is_lucky === "boolean") params.set("is_lucky", `eq.${is_lucky}`);
    if (query) {
      const q = query.replace(/[%,]/g, "");
      params.set("or", `(name->>th.ilike.*${q}*,name->>en.ilike.*${q}*)`);
    }
    const rows = await queryExternal(`supplies?${params}`);
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { supplies: rows }
    };
  }
});

// src/lib/mcp/tools/get-supply.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_supply_default = defineTool4({
  name: "get_supply",
  title: "Get supply",
  description: "Get a single supply/product by id.",
  inputSchema: { id: z4.string().min(1) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const [rows, variants] = await Promise.all([
      queryExternal(`supplies?id=eq.${encodeURIComponent(id)}&select=*&limit=1`),
      queryExternal(
        `supply_variants?supply_id=eq.${encodeURIComponent(id)}&select=*&order=sort_order.asc`
      ).catch(() => [])
    ]);
    const supply = rows?.[0];
    if (!supply) {
      return { content: [{ type: "text", text: `Supply ${id} not found` }], isError: true };
    }
    const withVariants = { ...supply, variants: variants ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(withVariants) }],
      structuredContent: { supply: withVariants }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_categories_default = defineTool5({
  name: "list_categories",
  title: "List categories",
  description: "List all plant/product categories with Thai and English names.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const rows = await queryExternal(
      `categories?select=key,emoji,color,name,sort_order&order=sort_order.asc`
    );
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { categories: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "treekingdom-mcp",
  title: "TreeKingdom MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the TreeKingdom bilingual (TH/EN) plant encyclopedia and lucky-plant store. Use list_categories to discover category keys, list_plants / get_plant for encyclopedia data (with care levels and varieties), and list_supplies / get_supply for store products (set is_lucky=true for auspicious plants).",
  tools: [list_categories_default, list_plants_default, get_plant_default, list_supplies_default, get_supply_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
